---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - name: include package tasks
      import_tasks: tasks/users.yml
      import_tasks: tasks/cron.yml
      import_tasks: tasks/packages.yml
